### ISSUE TITLE
[Suggestion] Allow saving System Configurations

### ISSUE THREAD

**Issue by Zeffuro** [NeNeppie/LightsCameraAction#1]
I would love if there was a way to save system configurations, for example I play with very low settings for raiding because my GTX 1060 sucks but I'd love to take screenshots with better graphic settings but screenshotting all of my settings has been a pain so far 😅 

I would love it if you could consider this option or if you don't plan to, maybe consider it as a separate plugin.

**Comment by NeNeppie** [comment]
I have no plans to deal with Character or System Configurations, and right now my project backlog is too large for me to consider a new plugin. I can only recommend a few things:
* You can try asking in Dalamud's discord. Such a plugin doesn't exist yet, but if demand is high enough someone might take on the job.
* You can alleviate the pain of constantly changing graphical settings by delegating settings like FXAA and AO to Reshade. There are also plugins that deal with shadows and resolution (See `SimpleTweaks` or `XIVWIndowResizer`)
* The game stores system configurations at `%USERPROFILE%\Documents\My Games\FINAL FANTASY XIV - A Realm Reborn\FFXIV.cfg`. Try to make a modified copy of this file and see whether swapping between the two changes the settings in real time.
