### ISSUE TITLE
Api Update / Dawntrail

### ISSUE THREAD

**Issue by dope250** [NeNeppie/LightsCameraAction#2]
Will there be an update for Dawntrail / Api 10?

I did try it myself but since it also needs an update to the hex signatures on _GameFunctions.cs_ I'm pretty lost there.

**Comment by NeNeppie** [comment]
I do intend on coming back to this. I haven't had much time with all the new content but expect an (proper) update soon 😄

**Comment by Solandus** [comment]
Hey there, anything new on this? Really miss it.

**Comment by NeNeppie** [comment]
Hi! Very very sorry for the long delay. I'm having a slight refactoring issue, but I believe I can push an update out later today, actually!

**Comment by NeNeppie** [comment]
And it's live on the testing branch. Happy Gposing!
